# The Python Interface

In [1]:
from IPython.display import HTML
HTML('<iframe src=ch1_slides.pdf width=700 height=450></iframe>')

In [2]:
# Example, do not modify!
print(5 / 8)

# Put code below here
print(7+10)

0.625
17


### Python is a pretty versatile language. For which applications can you use Python?

* You want to do some quick calculations.

* For your new business, you want to develop a database-driven website.

* Your boss asks you to clean and analyze the results of the latest satisfaction survey.

In [3]:
# Python as a calculator

# Addition and subtraction
print(5 + 5)
print(5 - 5)

# Multiplication and division
print(3 * 5)
print(10 / 2)

# Exponentiation
print(4 ** 2)

# Modulo
print(18 % 7)

# How much is your $100 worth after 7 years?
now = 100
for i in range(1,8):
    now = now * 1.1
print (now)  

10
0
15
5.0
16
4
194.87171000000015


In [4]:
# Variable Assignment

# Create a variable savings
savings = 100

# Print out savings
print (savings)

100


In [5]:
# Type conversion

# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float

pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


# List

As opposed to int, bool etc., a list is a compound data type; you can group values together:
```
a = "is"
b = "nice"
my_list = ["my", "list", a, b]
```

In [6]:
from IPython.display import HTML
HTML('<iframe src=ch2_slides.pdf width=700 height=450></iframe>')

In [7]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas

areas = [hall,kit,liv,bed,bath] 

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [8]:
# Slicing and dicing

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [9]:
# Extend a list

# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1

areas_1 = areas + ["poolhouse", 24.5]
# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage" , 15.45]

In [10]:
# Delete list elements

x = ["a", "b", "c", "d"]
#del(x[1])

In [11]:
# Inner workings of lists
# If you want to prevent changes in areas_copy to also take effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with list() or by using [:].
# Watch out! list() and [:] might not copy properly if you put complex things in your lists.


# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## Function

In [12]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

<class 'list'>
4


In [13]:
from IPython.display import HTML
HTML('<iframe src=ch3_slides.pdf width=700 height=450></iframe>')

In [14]:
# know about function 

help(max)
?max

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [15]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first  + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse =True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [16]:
# string to experiment with: room
room = "poolhouse"

# Use upper() on room: room_up
room_up = (room.upper())

# Print out room and room_up
print(room)
print(room_up)

# Print out the number of o's in room
print(room.count("o"))

poolhouse
POOLHOUSE
3


In [17]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20))

# Print out how often 14.5 appears in areas
print(areas.count(14.5))

2
0


In [18]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)


# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [19]:
# Definition of radius
r = 0.43

# Import the math package

import math
# Calculate C
C = 2 * math.pi * r

# Calculate A
A = math.pi * r * r

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [20]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


## Numpy

In [21]:
from IPython.display import HTML
HTML('<iframe src=ch4_slides.pdf width=700 height=450></iframe>')

In [22]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [23]:
# height is available as a regular list
height = [1, 2 ,34] 
# Import numpy
import numpy as np

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254 

# Print np_height_m
print(np_height_m)

[ 1  2 34]
[ 0.0254  0.0508  0.8636]


In [24]:
# height and weight are available as a regular lists
weight = [1, 2, 4]
height = [1,3,253]
# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg  / (np_height_m ** 2)

# Print out bmi
print(bmi)

[  7.03069006e+02   1.56237557e+02   4.39356344e-02]


In [25]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)
# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])


[False False  True]
[ 0.04393563]


In [26]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [27]:
# baseball is available as a regular list of lists
baseball = [["a", "b"], ["c", "d"]]
# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[1,:])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[0,0])

['c' 'd']
a


In [28]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array
updated = [[5, 3], [8, 7]]
baseball = [[5, 3], [8, 7]]
# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion =  np.array([0.0254, 0.453592])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[10  6]
 [16 14]]
[[ 0.127     1.360776]
 [ 0.2032    3.175144]]


In [29]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height from np_baseball
np_height = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

6.5
6.5


In [30]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 6.5
Median: 6.5
Standard Deviation: 1.5
Correlation: [[ 1.  1.]
 [ 1.  1.]]


In [31]:
# heights and positions are available as lists

heights = [1,25,4,6,45,7]
positions = ['GK','GK',"sdfj",'GK','Oth','GK']

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']


# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 6.5
Median height of other players: 24.5
